---
kind: pipeline
name: node-lts

trigger:
  branch:
  - master
  event:
  - push
  - pull_request

platform:
  os: linux
  arch: amd64 
 
steps:
- name: test
  image: node:14.18
  # temp
  failure: ignore
  commands:
  - npm install
  - npm test

- name: build
  image: node:14.18
  commands:
  - npm install
  - npm run build

---
kind: pipeline
name: node-latest

trigger:
  branch:
  - master
  event:
  - push
  - pull_request

platform:
  os: linux
  arch: amd64

steps:
- name: test
  image: node:16.10
  # temp
  failure: ignore
  commands:
  - npm install
  - npm test

- name: build
  image: node:16.10
  commands:
  - npm install
  - npm run build

